from pydantic import (
    BaseModel,
    Field,
)


class TripPlanRequest(BaseModel):

    user_id: int = Field(
        gt=0,
        description=(
            "Database ID of the user "
            "requesting the trip plan."
        ),
    )

    user_query: str = Field(
        min_length=3,
        max_length=4000,
        description=(
            "Natural-language travel request "
            "submitted by the user."
        ),
    )

class AgentResultResponse(BaseModel):

    answer: str

    tools_used: list[str] = Field(
        default_factory=list
    )

    is_complete: bool

class TripPlanResponse(BaseModel):

    final_response: str | None = Field(
        default=None,
        description=(
            "Final response generated by TripMate."
        ),
    )

    itinerary: str | None = Field(
        default=None,
        description=(
            "Generated itinerary when one "
            "was requested."
        ),
    )

    flight_result: AgentResultResponse | None = None

    hotel_result: AgentResultResponse | None = None

    weather_result: AgentResultResponse | None = None

    places_result: AgentResultResponse | None = None

    required_agents: list[str] = Field(
        default_factory=list,
        description=(
            "Specialist agents selected by "
            "the orchestrator."
        ),
    )

    completed_agents: list[str] = Field(
        default_factory=list,
        description=(
            "Specialist agents that completed "
            "successfully."
        ),
    )

    failed_agents: list[str] = Field(
        default_factory=list,
        description=(
            "Specialist agents that failed "
            "during workflow execution."
        ),
    )

    memory_loaded: bool = Field(
        default=False,
        description=(
            "Whether previous trip memory "
            "was loaded for this request."
        ),
    )

    trip_saved: bool = Field(
        default=False,
        description=(
            "Whether the completed trip was "
            "successfully persisted."
        ),
    )

    saved_trip_id: int | None = Field(
        default=None,
        description=(
            "Database ID of the saved trip."
        ),
    )

class TripHistoryItem(BaseModel):

    id: int

    origin: str | None = None
    destination: str | None = None

    start_date: str | None = None
    end_date: str | None = None

    budget: float | None = None

    adults: int | None = None
    children: int | None = None

    user_query: str

    itinerary: str | None = None
    final_response: str | None = None

    created_at: str | None = None


class TripHistoryResponse(BaseModel):

    user_id: int

    total_trips: int

    trips: list[
        TripHistoryItem
    ] = Field(
        default_factory=list
    )


class SavedTripResponse(BaseModel):

    id: int

    user_id: int

    origin: str | None = None
    destination: str | None = None

    start_date: str | None = None
    end_date: str | None = None

    budget: float | None = None

    adults: int | None = None
    children: int | None = None

    user_query: str

    itinerary: str | None = None
    final_response: str | None = None

class UserCreateRequest(BaseModel):

    name: str = Field(
        min_length=2,
        max_length=100,
        description="User's display name.",
    )

    email: str = Field(
        min_length=5,
        max_length=255,
        description="User's email address.",
    )


class UserResponse(BaseModel):

    id: int

    name: str

    email: str

    created_at: str | None = None